### ISSUE TITLE
Python example using pycrypto

### ISSUE THREAD

**Issue by MrJonRoberts** [TheAlphaSchoolSystemPTYLTD/api-introduction#10]
pycrypto has not been updated since 2013 - pycryptodome is an stand in.

This update requires the following changes on line 47.  

ciphertext = rijndael.encrypt(plaintext.encode("utf8"))

unable to test if it works or not as I am new to the TASS API and had to make these changes to get it to run with python 3.7.

**Comment by team-hq** [comment]
I know this is an old unanswered question (like all the others on this account :)) but that indeed works. I just installed pycryptodome and had to encode the str as per your code above.
