### ISSUE TITLE
flex_code parameter

### ISSUE THREAD

**Issue by dgoldsworthy** [TheAlphaSchoolSystemPTYLTD/api-introduction#18]
The General Ledger Analytics repo has a method **getCOA**

This has two optional parameters: flex_code and start_num.
I’m unable to find any information about these values, and our Finance Director has never heard of the flex code. Can you please let me know what these are?

Optional:

start_num [integer] - start_num required if flex_code supplied

flex_code [string] - flex_code required if start_num supplied

**Comment by scottetass** [comment]
Hi,

flex_code refers to the segment code in the general ledger setup.

![image](https://github.com/TheAlphaSchoolSystemPTYLTD/api-introduction/assets/149555853/aca827ff-4848-4607-bd8c-5d6ac8768251)
